version: "3.8"

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: client
    container_name: react-client
    working_dir: /app
    environment:
      API_URL: http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - api
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api:
    build: ./backend
    container_name: node-server
    image: server
    working_dir: /app
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
